config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :match_histories
  resources :users
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/match_history.rb
# frozen_string_literal: true

class MatchHistory < ApplicationRecord
  include EloHelper

  belongs_to :first_player, class_name: 'User'
  belongs_to :second_player, class_name: 'User'
  belongs_to :winner, class_name: 'User'

  validates :first_player, :second_player, :first_player_points, :second_player_points, :first_player_elo, :second_player_elo, :elo_change, :winner,
            presence: true
  validates :first_player_points, :second_player_points, :first_player_elo, :second_player_elo, :elo_change,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :winner, inclusion: { in: -> (match) { [match.first_player, match.second_player] } }
  validate :first_player_and_second_player_are_different

  after_create :update_users_data

  private

  def first_player_and_second_player_are_different
    errors.add(:second_player, 'must be different from first player') if first_player == second_player
  end

  def update_users_data
    winner.win_streak += 1
    winner.total_match += 1
    winner.total_win_match += 1

    loser = [first_player, second_player].find { |player| player != winner }
    loser.win_streak = 0
    loser.total_match += 1

    winner.elo += elo_change
    loser.elo -= elo_change

    loser.save!
    winner.save!
  end
end

app/controllers/match_histories_controller.rb
# frozen_string_literal: true

class MatchHistoriesController < ApplicationController
  include EloHelper
  before_action :set_match_history, only: %i[show edit update destroy]

  # GET /match_histories or /match_histories.json
  def index
    @match_histories = MatchHistory.all
  end

  # GET /match_histories/1 or /match_histories/1.json
  def show; end

  # GET /match_histories/new
  def new
    @match_history = MatchHistory.new
  end

  # GET /match_histories/1/edit
  def edit; end

  # POST /match_histories or /match_histories.json
  def create
    return render(:edit, status: :unprocessable_entity) if match_history_params[:first_player_points] == match_history_params[:second_player_points]

    first_player = User.find_by(id: match_history_params[:first_player_id])
    second_player = User.find_by(id: match_history_params[:second_player_id])
    winner_id = get_winner_id(first_player.id, second_player.id, match_history_params[:first_player_points],
                              match_history_params[:second_player_points]
    )

    return render(:edit, status: :unprocessable_entity) if first_player.nil? || second_player.nil?

    elo_change = if first_player.id == winner_id
                   elo_rating(first_player.elo, second_player.elo)
                 else
                   elo_rating(second_player.elo, first_player.elo)
                 end

    match_history_data = match_history_params.merge(winner_id: winner_id,
                                                    first_player_elo: first_player.elo,
                                                    second_player_elo: second_player.elo,
                                                    elo_change: elo_change
                                                   )

    @match_history = MatchHistory.new(match_history_data)
    @match_history.save!

    redirect_to(root_path)
  end

  # PATCH/PUT /match_histories/1 or /match_histories/1.json
  def update
    respond_to do |format|
      if @match_history.update(match_history_params)
        format.html { redirect_to(@match_history, notice: 'Match history was successfully updated.') }
        format.json { render(:show, status: :ok, location: @match_history) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @match_history.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /match_histories/1 or /match_histories/1.json
  def destroy
    @match_history.destroy!

    respond_to do |format|
      format.html { redirect_to(match_histories_path, status: :see_other, notice: 'Match history was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_match_history
    @match_history = MatchHistory.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def match_history_params
    params.require(:match_history).permit(:first_player_id, :second_player_id, :first_player_points, :second_player_points, :first_player_elo,
                                          :second_player_elo, :elo_change, :winner_id
    )
  end

  def get_winner_id(first_player_id, second_player_id, first_player_points, second_player_points)
    return first_player_id if Integer(first_player_points, 10) > Integer(second_player_points, 10)

    second_player_id
  end
end

app/helpers/match_histories_helper.rb
# frozen_string_literal: true

module MatchHistoriesHelper
end

app/views/match_histories/_form.html.erb
<div class="w-full max-w-xl mx-auto bg-white shadow-md rounded-lg overflow-hidden">
  <div class="px-6 py-4 bg-gray-50 border-b border-gray-200">
    <h2 class="text-xl font-semibold text-center text-gray-800">Add Match Result</h2>
  </div>
  <%= form_with(model: @match_history, local: true, class: "px-6 py-4 space-y-6") do |form| %>
    <span><%= @match_history.errors.full_messages %></span>
    <div class="grid grid-cols-[1fr,auto,1fr] items-center gap-4" data-controller="match-history">
      <!-- Player A Selection -->
      <div class="space-y-2">
        <%= form.select :first_player_id, 
            User.all.collect { |p| [p.name, p.id] }, 
            { }, 
            {
              class: "w-full px-3 py-2 text-gray-700 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 select2",
              data: { "match-history-target" => "firstPlayerSelect", "action" => "change->match-history#updateDisabledOption" }
            }
        %>
        <%= form.number_field :first_player_points, 
            placeholder: "Points", 
            min: 0, 
            class: "w-full px-3 py-2 mt-2 text-gray-700 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
        %>
      </div>
      <!-- VS Divider -->
      <div class="text-xl font-semibold self-start mt-2 text-gray-600">VS</div>
      <!-- Player B Selection -->
      <div class="space-y-2">
        <%= form.select :second_player_id, 
            User.all.collect { |p| [p.name, p.id] }, 
            { }, 
            {
              class: "w-full px-3 py-2 text-gray-700 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 select2",
              data: { "match-history-target" => "secondPlayerSelect", "action" => "change->match-history#updateDisabledOption" }
            }
        %>
        <%= form.number_field :second_player_points, 
            {
              placeholder: "Points", 
              min: 0, 
              class: "w-full px-3 py-2 mt-2 text-gray-700 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600" 
            }
        %>
      </div>
    </div>
    <%= form.submit "Submit Result", 
        class: "w-full px-4 py-2 mt-6 font-semibold text-white bg-blue-600 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50" 
    %>
  <% end %>
</div>

app/views/match_histories/_match_history.html.erb
<div id="<%= dom_id match_history %>">
</div>

app/views/match_histories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing match history</h1>

  <%= render "form", match_history: @match_history %>

  <%= link_to "Show this match history", @match_history, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to match histories", match_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/match_histories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% content_for :title, "Match histories" %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Match histories</h1>
    <%= link_to "New match history", new_match_history_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="match_histories" class="min-w-full">
    <% @match_histories.each do |match_history| %>
      <%= render match_history %>
      <p>
        <%= link_to "Show this match history", match_history, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/match_histories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", match_history: @match_history %>
  <%= link_to "Back to home", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/match_histories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @match_history %>

    <%= link_to "Edit this match history", edit_match_history_path(@match_history), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to match histories", match_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this match history", @match_history, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>