config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :match_histories
  resources :users
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include UsersHelper
  def index
    users = User.all.order(elo: :desc)
    total_users = users.count
    @aggregate_users = users.each_with_index.map do |user, index|
      user_info(user, index, total_users)
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<div class="min-h-screen bg-zinc-950 p-6">
  <div class="mx-auto max-w-7xl">
    <div class="mb-6 flex items-center justify-between">
      <h1 class="text-2xl font-bold text-white">Leaderboard</h1>
      <div class="space-x-4">
        <%= link_to new_user_path, class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent text-white hover:text-accent-foreground h-10 px-4 py-2" do %>
          <%= icon "plus-circle", class: "h-4 w-4 mr-2" %>
          Add New Player
        <% end %>
        <%= link_to new_match_history_path, class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-white text-primary-foreground hover:bg-white/90 h-10 px-4 py-2" do %>
          <%= icon "plus-circle", class: "h-4 w-4 mr-2" %>
          Add Match Result
        <% end %>
      </div>
    </div>
    <div class="rounded-lg border border-zinc-800 bg-zinc-900">
      <table class="w-full">
        <thead>
          <tr class="border-b border-zinc-800 text-sm text-zinc-400">
            <th class="p-4 text-left">#</th>
            <th class="p-4 text-left">Player</th>
            <th class="p-4 text-left">Tier</th>
            <th class="p-4 text-left">Elo</th>
            <th class="p-4 text-left">W</th>
            <th class="p-4 text-left">L</th>
            <th class="p-4 text-left">Win rate</th>
          </tr>
        </thead>
        <tbody>
          <% @aggregate_users.each_with_index do |aggregate_users, index| %>
            <tr class="border-b border-zinc-800 text-sm text-zinc-100 hover:bg-zinc-700 cursor-pointer <%= 'last:border-0' if index == @aggregate_users.size - 1 %>"
              data-controller="home" data-home-url-value="<%= user_path(aggregate_users[:user]) %>" data-action="click->home#goToUrl">
              <td class="p-4"><%= index + 1 %></td>
              <td class="p-4">
                <div class="flex items-center space-x-3">
                  <div class="h-8 w-8 rounded-full bg-zinc-800"></div>
                  <div class="flex flex-col gap-1">
                    <div class="font-medium"><%= aggregate_users[:user].name  %></div>
                    <div class="flex flex-row gap-0.5 items-center text-xs text-zinc-400">
                      <%= image_tag(aggregate_users[:flame_icon], width: 20) %>
                      <span>
                        <%= aggregate_users[:user].win_streak %>
                      </span>
                    </div>
                  </div>
                </div>
              </td>
              <td class="p-4">
                <div class="flex flex-row gap-1.5 items-center text-xs text-zinc-400">
                  <%= image_tag(aggregate_users[:tier] + ".png", width: 35) %>
                  <span>
                    <%= aggregate_users[:tier] %>
                  </span>
                </div>
              </td>
              <td class="p-4"><%= aggregate_users[:user].elo %></td>
              <td class="p-4"><%= aggregate_users[:wins] %></td>
              <td class="p-4"><%= aggregate_users[:losses] %></td>
              <td class="p-4">
                <div class="flex items-center space-x-3">
                  <div class="h-2 w-32 overflow-hidden rounded-full bg-zinc-800">
                    <div class="h-full bg-gradient-to-r from-blue-500 to-red-500" style="width: <%=aggregate_users[:win_rate] || 0 %>%;"></div>
                  </div>
                  <span class="text-xs"><%= aggregate_users[:win_rate] %>%</span>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>